(() => {
'use strict';
const STORAGE_KEY='typing-game-v1';
const words='focus keyboard moment practice velocity accuracy rhythm future signal create bright system engine mastery simple power curious build learn level streak challenge player rapid clean smooth control timing progress skill winning energy precision habit memory pattern better stronger faster steady confident sharp typing developer browser interface creative project launch quality design coding terminal network secure digital coffee midnight sunrise galaxy thunder forest river ocean journey adventure mission legend victory signal quantum rocket pixel neon future dream momentum focus discipline consistency performance strategy attention reaction language sentence paragraph master improve repeat adapt climb unlock achievement record personal speed arena daily training'.split(' ');
const sentences=['Small improvements become massive results when you repeat them every day.','The fastest typists are not always the most accurate, but the best players become both.','Stay relaxed, watch the next word, and let your fingers follow the rhythm.','Consistency is a skill you can train one clean sentence at a time.','Great speed comes from fewer mistakes, better focus, and deliberate practice.','Build your flow, protect your combo, and push your personal record a little higher.','A calm mind and a precise keyboard can turn practice into effortless performance.'];
const state={mode:'classic',running:false,startedAt:0,elapsed:0,duration:30,prompt:'',typed:'',correct:0,errors:0,combo:0,bestCombo:0,score:0,lastWpm:0,lastAccuracy:100,timerId:null,data:loadData(),sound:true,theme:localStorage.getItem('typing-theme')||'dark'};
const $=id=>document.getElementById(id); const refs={wpm:$('wpm'),accuracy:$('accuracy'),combo:$('combo'),timer:$('timer'),progress:$('progressBar'),prompt:$('prompt'),input:$('typingInput'),correct:$('correctChars'),errors:$('errors'),bestCombo:$('bestCombo'),start:$('startBtn'),restart:$('restartBtn'),heroBest:$('heroBest'),heroBestMeta:$('heroBestMeta'),level:$('levelLabel'),difficulty:$('difficultyLabel'),toast:$('toast'),sound:$('soundToggle'),theme:$('themeToggle'),statsOpen:$('statsOpen'),statsDialog:$('statsDialog'),statsClose:$('statsClose'),resetStats:$('resetStats'),dialogBestWpm:$('dialogBestWpm'),dialogBestAcc:$('dialogBestAcc'),dialogRuns:$('dialogRuns'),dialogChars:$('dialogChars'),achievements:$('achievements'),achievementCount:$('achievementCount'),gameCard:$('gameCard'),typingShell:document.querySelector('.typing-shell')};
const achievements=[['first-run','🚀','First Run','Finish your first game'],['speed-30','⚡','30 WPM','Reach 30 WPM'],['speed-50','🔥','50 WPM','Reach 50 WPM'],['speed-80','💨','80 WPM','Reach 80 WPM'],['accuracy-95','🎯','Sharpshooter','Finish with 95%+ accuracy'],['combo-30','⛓️','Chain Master','Reach a 30× combo'],['perfect','💎','Flawless','Finish a run with 100% accuracy'],['runs-10','🏅','Regular','Complete 10 runs']];
function loadData(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{bestWpm:0,bestAccuracy:0,runs:0,totalChars:0,totalCorrect:0,unlocked:[]}}catch{return{bestWpm:0,bestAccuracy:0,runs:0,totalChars:0,totalCorrect:0,unlocked:[]}}}
function saveData(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state.data))} function applyTheme(){document.documentElement.classList.toggle('light',state.theme==='light');refs.theme.textContent=state.theme==='light'?'☀':'◐'} function randomItem(a){return a[Math.floor(Math.random()*a.length)]}
function makePrompt(){if(state.mode==='challenge')return randomItem(sentences)+' '+randomItem(sentences).split(' ').slice(0,5).join(' ')+'.';if(state.mode==='zen')return randomItem(sentences);const chosen=[];for(let i=0;i<18+Math.floor(Math.random()*12);i++)chosen.push(randomItem(words));return chosen.join(' ')}
function getDuration(){return state.mode==='zen'?60:state.mode==='challenge'?45:30} function levelMeta(w){if(w>=80)return['LEVEL 8 · VELOCITY','Elite'];if(w>=60)return['LEVEL 6 · TURBO','Expert'];if(w>=45)return['LEVEL 4 · FLOW','Advanced'];if(w>=30)return['LEVEL 3 · PACE','Intermediate'];if(w>=18)return['LEVEL 2 · RHYTHM','Rising'];return['LEVEL 1 · WARM-UP','Beginner']}
function renderPrompt(){const f=document.createDocumentFragment();[...state.prompt].forEach((c,i)=>{const s=document.createElement('span');s.textContent=c;if(i<state.typed.length)s.className=state.typed[i]===c?'correct':'wrong';if(i===state.typed.length)s.classList.add('current');f.appendChild(s)});refs.prompt.replaceChildren(f)}
function elapsedSeconds(){return state.running?(Date.now()-state.startedAt)/1000:state.elapsed} function calcWpm(){return Math.max(0,Math.round((state.correct/5)/Math.max(elapsedSeconds()/60,1/60)))} function calcAccuracy(){const t=state.correct+state.errors;return t?Math.max(0,Math.round(state.correct/t*100)):100} function comboMultiplier(){return 1+Math.min(4,Math.floor(state.combo/10)*.25)}
function updateUI(){const w=calcWpm(),a=calcAccuracy();state.lastWpm=w;state.lastAccuracy=a;refs.wpm.textContent=w;refs.accuracy.textContent=a+'%';refs.combo.textContent=state.combo+'×';refs.correct.textContent=state.correct;refs.errors.textContent=state.errors;refs.bestCombo.textContent=state.bestCombo;const remaining=Math.max(0,state.duration-elapsedSeconds());refs.timer.textContent=state.mode==='zen'?'∞':Math.ceil(remaining);refs.progress.style.width=(state.mode==='zen'?0:Math.min(100,elapsedSeconds()/state.duration*100))+'%';const [l,d]=levelMeta(w);refs.level.textContent=l;refs.difficulty.textContent=d;refs.heroBest.textContent=state.data.bestWpm+' WPM';refs.heroBestMeta.textContent=state.data.runs?state.data.runs+' completed runs':'No runs yet';refs.start.innerHTML=state.running?'Pause Game <kbd>Space</kbd>':(state.elapsed>0?'Resume Game <kbd>Space</kbd>':'Start Game <kbd>Space</kbd>');renderPrompt()}
function resetSession(){clearInterval(state.timerId);state.timerId=null;state.running=false;state.startedAt=0;state.elapsed=0;state.duration=getDuration();state.prompt=makePrompt();state.typed='';state.correct=0;state.errors=0;state.combo=0;state.bestCombo=0;state.score=0;refs.input.value='';refs.input.disabled=true;updateUI()}
function startGame(){if(state.running){pauseGame();return}state.running=true;state.startedAt=Date.now()-state.elapsed*1000;refs.input.disabled=false;refs.input.focus();state.timerId=setInterval(tick,100);updateUI();playTone(620,.04)} function pauseGame(){state.elapsed=Math.min(state.duration,elapsedSeconds());state.running=false;clearInterval(state.timerId);state.timerId=null;updateUI()} function tick(){if(state.mode!=='zen'&&elapsedSeconds()>=state.duration){finishGame();return}updateUI()}
function finishGame(){state.elapsed=Math.min(state.duration,elapsedSeconds());state.running=false;clearInterval(state.timerId);state.timerId=null;refs.input.disabled=true;const w=calcWpm(),a=calcAccuracy();state.data.runs++;state.data.totalChars+=state.typed.length;state.data.totalCorrect+=state.correct;if(w>state.data.bestWpm)state.data.bestWpm=w;if(a>state.data.bestAccuracy)state.data.bestAccuracy=a;state.data.unlocked=[...new Set([...state.data.unlocked,...checkAchievements(w,a)])];saveData();updateUI();updateStatsDialog();refs.gameCard.classList.add('pulse');setTimeout(()=>refs.gameCard.classList.remove('pulse'),350);toast(`Run complete — ${w} WPM at ${a}% accuracy.`);playTone(w>=50?980:720,.11)}
function checkAchievements(w,a){const out=[],u=new Set(state.data.unlocked);if(state.data.runs>=1&&!u.has('first-run'))out.push('first-run');if(w>=30&&!u.has('speed-30'))out.push('speed-30');if(w>=50&&!u.has('speed-50'))out.push('speed-50');if(w>=80&&!u.has('speed-80'))out.push('speed-80');if(a>=95&&!u.has('accuracy-95'))out.push('accuracy-95');if(state.bestCombo>=30&&!u.has('combo-30'))out.push('combo-30');if(a===100&&!u.has('perfect'))out.push('perfect');if(state.data.runs>=10&&!u.has('runs-10'))out.push('runs-10');return out}
function onInput(){if(!state.running)return;const value=refs.input.value;if(value.length>state.prompt.length){refs.input.value=value.slice(0,state.prompt.length);return}const old=state.typed;state.typed=value;for(let i=old.length;i<value.length;i++){if(value[i]===state.prompt[i]){state.correct++;state.combo++;state.bestCombo=Math.max(state.bestCombo,state.combo);state.score+=Math.round(10*comboMultiplier());playTone(540+Math.min(300,state.combo*4),.015)}else{state.errors++;state.combo=0;refs.typingShell.classList.add('shake');setTimeout(()=>refs.typingShell.classList.remove('shake'),220);playTone(180,.04)}}if(state.typed===state.prompt){state.elapsed=elapsedSeconds();state.prompt=makePrompt();state.typed='';refs.input.value=''}updateUI()}
function playTone(freq,duration){if(!state.sound)return;try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;const ctx=playTone.ctx||(playTone.ctx=new AC()),o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.035,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+duration);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+duration)}catch{}}
function toast(msg){refs.toast.textContent=msg;refs.toast.classList.add('show');clearTimeout(toast.id);toast.id=setTimeout(()=>refs.toast.classList.remove('show'),2400)}
function updateStatsDialog(){refs.dialogBestWpm.textContent=state.data.bestWpm;refs.dialogBestAcc.textContent=state.data.bestAccuracy+'%';refs.dialogRuns.textContent=state.data.runs;refs.dialogChars.textContent=state.data.totalChars;refs.achievementCount.textContent=`${state.data.unlocked.length}/${achievements.length}`;refs.achievements.replaceChildren(...achievements.map(([id,icon,title,desc])=>{const d=document.createElement('div');d.className='achievement'+(state.data.unlocked.includes(id)?' unlocked':'');d.innerHTML=`<div class="achievement-icon">${icon}</div><div><strong>${title}</strong><small>${desc}</small></div>`;return d}))}
function setMode(mode){if(state.running)pauseGame();state.mode=mode;resetSession();document.querySelectorAll('.mode-btn').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));toast(mode[0].toUpperCase()+mode.slice(1)+' mode selected')}
refs.input.addEventListener('input',onInput);refs.start.addEventListener('click',startGame);refs.restart.addEventListener('click',resetSession);document.querySelectorAll('.mode-btn').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));refs.sound.addEventListener('click',()=>{state.sound=!state.sound;refs.sound.textContent=state.sound?'🔊':'🔇'});refs.theme.addEventListener('click',()=>{state.theme=state.theme==='dark'?'light':'dark';localStorage.setItem('typing-theme',state.theme);applyTheme()});refs.statsOpen.addEventListener('click',()=>{updateStatsDialog();refs.statsDialog.showModal()});refs.statsClose.addEventListener('click',()=>refs.statsDialog.close());refs.resetStats.addEventListener('click',()=>{if(confirm('Reset all local progress?')){state.data={bestWpm:0,bestAccuracy:0,runs:0,totalChars:0,totalCorrect:0,unlocked:[]};saveData();updateStatsDialog();updateUI();toast('Progress reset.')}});document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='r'&&document.activeElement!==refs.input){e.preventDefault();resetSession()}if(e.code==='Space'&&document.activeElement!==refs.input){e.preventDefault();startGame()}if(e.key==='Escape'&&refs.statsDialog.open)refs.statsDialog.close()});applyTheme();resetSession();
})();
