(()=>{'use strict';
const $=s=>document.querySelector(s);const layer=$('#wordLayer'),input=$('#answer'),arena=$('#arena'),overlay=$('#overlay'),start=$('#start');
const WORDS=['apple','planet','rocket','thunder','forest','galaxy','keyboard','browser','coffee','midnight','shadow','energy','velocity','matrix','rhythm','signal','quantum','pixel','coding','victory','future','focus','typing','warrior','speed','engine','network','digital','secure','challenge','precision','momentum','horizon','phantom','crystal','storm','ember','neon','gravity','orbit','memory','pattern','master','rapid','smooth','control','timing','reaction','attention','discipline'];
const POWER=['SLOW','SHIELD','FRENZY'];
const S={running:false,score:0,combo:0,bestCombo:0,lives:3,level:1,wpm:0,correct:0,chars:0,misses:0,began:0,last:0,spawnClock:0,words:[],power:null,powerUntil:0,raf:0};
function reset(){cancelAnimationFrame(S.raf);S.running=false;S.score=0;S.combo=0;S.bestCombo=0;S.lives=3;S.level=1;S.wpm=0;S.correct=0;S.chars=0;S.misses=0;S.began=0;S.last=0;S.spawnClock=0;S.words=[];S.power=null;S.powerUntil=0;layer.innerHTML='';input.value='';paint();}
function paint(){const t=S.running?(performance.now()-S.began)/1000:0;S.wpm=S.correct?Math.round((S.chars/5)/Math.max(t/60,.01)):0;$('#score').textContent=S.score;$('#combo').textContent=S.combo+'×';$('#lives').textContent='♥'.repeat(S.lives)+'♡'.repeat(3-S.lives);$('#time').textContent=Math.floor(t)+'s';$('#wpm').textContent=S.wpm;const tag=$('#status');if(tag)tag.textContent=S.power?S.power:'READY';}
function difficulty(){return 1+Math.floor(S.score/500);}
function spawn(){const el=document.createElement('div');el.className='fall';const word=WORDS[Math.floor(Math.random()*WORDS.length)];el.textContent=word;el.style.left=(4+Math.random()*84)+'%';el.style.top='-50px';el.dataset.word=word;layer.appendChild(el);S.words.push({el,word,y:-50,v:48+Math.min(150,difficulty()*9)+Math.random()*18});}
function powerDrop(){const p=POWER[Math.floor(Math.random()*POWER.length)];S.power=p;S.powerUntil=performance.now()+6000;const toast=$('#powerToast');if(toast){toast.textContent=p==='SLOW'?'TIME SLOWED':p==='SHIELD'?'SHIELD READY':'FRENZY MODE';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1200);}paint();}
function hit(word){let i=S.words.findIndex(x=>x.word===word);if(i<0)return false;const x=S.words[i];x.el.remove();S.words.splice(i,1);S.combo++;S.bestCombo=Math.max(S.bestCombo,S.combo);S.correct++;S.chars+=word.length;let mult=1+Math.min(4,Math.floor(S.combo/5));if(S.power==='FRENZY')mult*=2;S.score+=10*mult;if(S.combo>0&&S.combo%12===0)powerDrop();return true;}
function miss(i){const x=S.words[i];if(!x)return;x.el.remove();S.words.splice(i,1);if(S.power==='SHIELD'){S.power=null;return;}S.lives--;S.combo=0;S.misses++;if(S.lives<=0)end();}
function onSubmit(){const w=input.value.trim().toLowerCase();if(!w)return;if(hit(w))input.value='';paint();input.focus();}
function end(){S.running=false;cancelAnimationFrame(S.raf);const best=Math.max(Number(localStorage.getItem('tg-best-v2')||0),S.score);localStorage.setItem('tg-best-v2',best);overlay.style.display='grid';overlay.querySelector('h1').textContent='RUN COMPLETE';overlay.querySelector('p').textContent=`Score ${S.score} · ${S.wpm} WPM · Best ${best}`;start.textContent='PLAY AGAIN';paint();}
function startRun(){reset();S.running=true;S.began=performance.now();S.last=S.began;overlay.style.display='none';input.focus();requestAnimationFrame(loop);}
function loop(now){if(!S.running)return;const dt=Math.min(.04,(now-S.last)/1000);S.last=now;S.spawnClock-=dt*1000;if(S.spawnClock<=0){spawn();S.spawnClock=Math.max(300,1050-difficulty()*85);}if(S.power&&now>S.powerUntil)S.power=null;const slow=S.power==='SLOW'?.42:1;for(let i=S.words.length-1;i>=0;i--){const x=S.words[i];x.y+=x.v*dt*slow;x.el.style.top=x.y+'px';if(x.y>arena.clientHeight-108)miss(i);}S.level=Math.min(10,difficulty());paint();S.raf=requestAnimationFrame(loop);}
start.addEventListener('click',startRun);$('#submit').addEventListener('click',onSubmit);input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();onSubmit();}});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&S.running){end();}});reset();
})();